name: neo4j-ipycytoscape 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python>=3.8
  - nodejs
  - jupyterlab=3
  - pandas
  - pip
  - pip:
    - py2neo
    - git+https://github.com/pwrose/ipycytoscape.git 
